#!/bin/bash

CONTAINER=`docker ps | grep Datasci | wc -l`
if [ ${CONTAINER}=0 ]; then
    docker start Datasci;
fi

### WSL2 on Windows 10 ### 
docker exec -it --user rstudio --env  DISPLAY=`cat /etc/resolv.conf | grep nameserver | awk '{print $2}'`:0.0 Datasci bash
